### ISSUE TITLE
should not print status

### ISSUE THREAD

**Issue by chuckha** [ashish-amarnath/capi-yaml-gen#17]
this should not print status to objects.

If necessary we could hide it behind a flag, but  I can't think of a use case right now that would ever necessitate needing the status object.

**Comment by chuckha** [comment]
This is going to be hacky no matter what. Since the status object is not any of these types:

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.

it will always be populated and printed which means we'll have to strip it out post-serialization.

**Comment by ashish-amarnath** [comment]
Agree that this is going to be hacky. So here it goes https://github.com/ashish-amarnath/capi-yaml-gen/pull/20

**Comment by ashish-amarnath** [comment]
Fixed
