### ISSUE TITLE
Improvements on the abstraction

### ISSUE THREAD

**Issue by chuckha** [ashish-amarnath/capi-yaml-gen#23]
The provider abstraction is still not quite there.

The providers should not have to know about the `generator.Object` type. This means we'll need to add one more layer to the abstraction.

We will need something that can wrap up the actual providers and keep that logic out of the generate.go file.

Something like this:

```
// generate.go
machineFactory, err := generator.NewMachineFactory(provider)
machine := machineFactory.Machine(name, namespace)

// generator.go

type Object interface {...}

// MachineFactory
type Factory struct {
  provider string
}

func NewFactory(provider string) (Factory, error) {
 // if provider is unknown return an error otherwise return a factory
}

func (f Factory) Machine(name, namespace string) Object {
  switch f.provider
  case "aws":
    capa.GenerateMachine()
  case "docker":
    capd.GenerateMachine()
  ...
}

// capd.go

// Notice the return type, no longer referencing generator.Object
func (p Provider) GenerateMachine(...arguments...) *infrav1.Machine {}
```

This would also negate the need for the `Provider` shell struct. The factory can just call the correct function from the correct package.

**Comment by ashish-amarnath** [comment]
I think we've made good progress on this and this issue can be closed.
@chuckha  WDYT?

**Comment by chuckha** [comment]
works for me!
