### ISSUE TITLE
Add some default values

### ISSUE THREAD

**Issue by chuckha** [ashish-amarnath/capi-yaml-gen#24]
We should start thinking about scenarios and how to get things like cloud provider flags piped into the right places.

If I am using kubeadm and i ask for the aws infrastructure provider, I should see all the required `cloud-provider: aws` flags in all the right places as well as a default secret I could fill in. In addition, we'd also need sshkey, iaminstance profile and instance size variables. I'm not sure a great way to get these values. But I think something like some YAML that can be run through envsubst would be great. Or perhaps we can accept a configuration file and output valid YAML? Perhaps both if no configuration is defined?

I'm not entirely sure how it would work yet as you can see, but this would be the start of something very useful imo.

At the very least we can put in the hardcoded defaults for AWS.

**Comment by chuckha** [comment]
Please see these links:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/examples/cluster/cluster.yaml#L7-L9

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/examples/controlplane/controlplane.yaml#L25-L27

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/examples/controlplane/controlplane.yaml#L82-L85

**Comment by ashish-amarnath** [comment]
To have  cloud  (infra)  provider flags flow into the core cluster yaml and the bootstrap provider config, we could update the  `InfrastructureProvider` interface w/ methods like `UpdateCoreCluster` and `UpdateBootstrapConfig` passing the objects to update/mutate as parameters. Infra provider implementation can perform the necessary mutations and return. 

Reading the first few lines of the description, I was considering a "variables" file to provide a mapping of variable to values, something like makefile variables file that we can look up for values and use defaults if the value for a variable isn't found- something like `ADD YOUR SECRET HERE`  os something.

WDYT?

**Comment by ashish-amarnath** [comment]
PR https://github.com/ashish-amarnath/capi-yaml-gen/pull/25 is the first step for this,
Next, we will support a variables map in something like a makefile variables file that can be used to do  envsubst like action

**Comment by chuckha** [comment]
I think this is closed, at least, as much as i need it to be
