### ISSUE TITLE
Add a tag for v1a2 and get support for v1a3

### ISSUE THREAD

**Issue by chuckha** [ashish-amarnath/capi-yaml-gen#35]
I suggest we add a branch or maybe a tag for v1alpha2 generation and then move master along to v1alpha3. I've got a PR i'm about to open to support v1alpha3 but I know for a fact i'll need v1alpha2 support as well and need to switch between the versions

**Comment by ashish-amarnath** [comment]
We have a branch w/ v1a2 generation https://github.com/ashish-amarnath/capi-yaml-gen/tree/v1a2
